$(document).ready(function(){
		$("#tPapel").hide();
		$("#tUv").hide();
		$("#m-contemporanea").hide();
		$("#m-moderna").hide();
		$("#bMeta").click(function(){
        $("#tPapel").hide();
		$("#tUv").hide();
        $("#tMeta").fadeIn();
    });
		$("#bPrints").click(function(){
        $("#tMeta").hide();
		$("#tUv").hide();
        $("#tPapel").fadeIn();
    });
		$("#bUv").click(function(){
        $("#tPapel").hide();
		$("#tMeta").hide();
        $("#tUv").fadeIn();
    });
		$("#b-classica").click(function(){
		$("#m-contemporanea").hide();
		$("#m-moderna").hide();
        $("#m-classica").fadeIn();
    });
		$("#b-contemporanea").click(function(){
        $("#m-classica").hide();
		$("#m-moderna").hide();
        $("#m-contemporanea").fadeIn();
    });
		$("#b-moderna").click(function(){
		$("#m-classica").hide();
		$("#m-contemporanea").hide();
        $("#m-moderna").fadeIn();
    });
		$("#tamanhoPersonalizado").hide();
		$("#b-tamanhoPersonalizado").click(function(){
			$("#tamanhoPadrao").hide();
			$("#tamanhoPersonalizado").fadeIn();
		});
		$("#b-tamanhoPadrao").click(function(){
			$("#tamanhoPersonalizado").hide();
			$("#tamanhoPadrao").fadeIn();
		});
});